require("maruf.plugins-setup")
require("maruf.core.options")
require("maruf.core.keymaps")
require("maruf.core.colorscheme")
require("maruf.plugins.comment")
require("maruf.plugins.nvim-tree")
require("maruf.plugins.lualine")
require("maruf.plugins.telescope")
require("maruf.plugins.nvim-cmp")
require("maruf.plugins.autopairs")
require("maruf.plugins.treesitter")
require("maruf.plugins.gitsigns")

require("maruf.plugins.lsp.mason")
require("maruf.plugins.lsp.lspsaga")
require("maruf.plugins.lsp.lspconfig")
require("maruf.plugins.lsp.null-ls")
